contact detail component
thames-valley-housing/mtvh-formio pull request #2
Opened 2022-07-29 11:13 UTC by francellanjones

Adds a custom component for contact details. 
Comes with:
   - prepopulated dropdown
   - selected number in the case of a TVH preferred number
   - option to add a new phone number
   - validation on inputted phone number

To test you can go to the example.html page to see it in action
Dropdown
![custom component dropdown](https://user-images.githubusercontent.com/82815765/181747369-a32905ca-3d90-46ff-be63-733c408d1090.PNG)
![custom component populated dropdown](https://user-images.githubusercontent.com/82815765/181747433-37801c99-f591-4e5a-b14c-75039dcecd35.PNG)
Freetext
![custom component freetext](https://user-images.githubusercontent.com/82815765/181747391-d988b7fd-2a2a-4b4e-95d9-12bb1d5c89b3.PNG)

2022-08-01 14:53 UTC, robbiepaul commented on package.json
> +  "version": "2.0.10",
Should we bump the version?
```suggestion
  "version": "2.1.0",
```

2022-08-01 14:53 UTC, robbiepaul commented on src/components/mtvhContactDetail/mtvhContactDetail.ts
> +    return this.refs.newDetailsInput.value.replace(/\W+/g, '');
Nice 👍

2022-08-01 14:53 UTC, robbiepaul commented on src/components/mtvhContactDetail/mtvhContactDetail.ts
> +
Let's remove these if they aren't required

```suggestion
```

2022-08-01 14:53 UTC, robbiepaul commented on src/templates/bootstrap/mtvhContactDetail/form.ejs
> +      <a ref="switchToDropdown", href="#">
```suggestion
      <a ref="switchToDropdown" href="#">
```

2022-08-01 14:53 UTC, robbiepaul commented on src/templates/bootstrap/mtvhContactDetail/form.ejs
> +      <a ref="switchToFreetext", href="#">
```suggestion
      <a ref="switchToFreetext" href="#">
```

2022-08-01 14:53 UTC, robbiepaul commented on fonts/fonts.css
> +}
Are these font changes needed?

2022-08-01 16:58 UTC, jmc-tv requested changes
Have the free-text entry of the email address make use of the already existing email typo suggestor we use elsewhere when users or agents enter an email.

2022-08-02 08:33 UTC, njall-mtvh commented
This isn't an email component @jmc-tv - it's only a phone number component. 

We are only doing the phone number component here because we decided that the email would: 
a) be just an acknowledgement that an SRQ has been raised to the default email, with no submission information attached so as not to risk GDPR issues
b) therefore not be necessary for the minimum viable product to add an email

2022-08-02 08:37 UTC, jmc-tv submitted a review, later dismissed

2022-08-02 08:38 UTC, jmc-tv commented
> This isn't an email component @jmc-tv - it's only a phone number component.
> 
> We are only doing the phone number component here because we decided that the email would: a) be just an acknowledgement that an SRQ has been raised to the default email, with no submission information attached so as not to risk GDPR issues b) therefore not be necessary for the minimum viable product to add an email

Grand so.

2022-08-02 08:49 UTC, njall-mtvh commented on fonts/fonts.css
> +}
🤷 https://github.com/thames-valley-housing/mtvh-formio/commits/e05b1586052a95a1ffbbbe2cd3dbf2f2126900cd/fonts/fonts.css

2022-08-02 08:51 UTC, njall-mtvh commented on fonts/fonts.css
> +}
Matts added it to this branch, but I wouldn't expect he'd want it to go live given the commit is `playing`. I'll remove it from this PR and let Matt know. Good spot!

2022-08-02 13:18 UTC, njall-mtvh commented on fonts/fonts.css
> +}
I dunno whether to remove it tbh. Can't tell if it'll be a problem or not... Any thoughts?

2022-08-02 13:46 UTC, robbiepaul approved these changes

2022-08-02 16:01 UTC, merged